// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHEOzkQQxge1Co4X9UjsOBu0eQXGBYoec',
    appId: '1:853441297981:web:e94388518336c2916d3454',
    messagingSenderId: '853441297981',
    projectId: 'flutterfirebase-7ca01',
    authDomain: 'flutterfirebase-7ca01.firebaseapp.com',
    databaseURL: 'https://flutterfirebase-7ca01-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7ca01.appspot.com',
    measurementId: 'G-XJW7F1GCWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpPmnsjmf4YK-coUI6sWlIi8biirXvR4I',
    appId: '1:853441297981:android:ed36b5dd1df6f5b06d3454',
    messagingSenderId: '853441297981',
    projectId: 'flutterfirebase-7ca01',
    databaseURL: 'https://flutterfirebase-7ca01-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7ca01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK3HEJZkCqjzzccJOoSsZ2fOELQeeSroM',
    appId: '1:853441297981:ios:d94c465d191a03786d3454',
    messagingSenderId: '853441297981',
    projectId: 'flutterfirebase-7ca01',
    databaseURL: 'https://flutterfirebase-7ca01-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7ca01.appspot.com',
    androidClientId: '853441297981-ldv59piq00k2p2nnlmvpiehgijsgktu5.apps.googleusercontent.com',
    iosClientId: '853441297981-9m740udge9rootmk79ht0ps7i7mq1ff1.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK3HEJZkCqjzzccJOoSsZ2fOELQeeSroM',
    appId: '1:853441297981:ios:d94c465d191a03786d3454',
    messagingSenderId: '853441297981',
    projectId: 'flutterfirebase-7ca01',
    databaseURL: 'https://flutterfirebase-7ca01-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebase-7ca01.appspot.com',
    androidClientId: '853441297981-ldv59piq00k2p2nnlmvpiehgijsgktu5.apps.googleusercontent.com',
    iosClientId: '853441297981-9m740udge9rootmk79ht0ps7i7mq1ff1.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnFlutter',
  );
}
